'use strict';
const API='https://tapsoniamas-api.onrender.com/api';
const categories=['Άλλα','Φρούτα','Λαχανικά','Κρέας','Ψάρια','Γαλακτοκομικά','Αρτοποιείο','Ποτά','Κατεψυγμένα','Καθαριστικά','Χαρτικά','Προσωπική φροντίδα','Σπίτι'];
const stores=['','Super Market','Lidl','Μανάβικο','Κρεοπωλείο','Φαρμακείο','Jumbo','Άλλο'];
const units=['κιλά','κιλό','kg','γρ','γραμμάρια','τεμάχια','τεμάχιο','μπουκάλια','μπουκάλι','πακέτα','πακέτο'];
let token=localStorage.getItem('psonia.token')||'',items=[],query='',household=null,eventSource=null,deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function show(sel){['#authView','#householdView','#appView'].forEach(s=>$(s).hidden=s!==sel)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2500)}
async function api(path,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};if(token)headers.authorization='Bearer '+token;const r=await fetch(API+path,{...opts,headers});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Κάτι πήγε στραβά.');return data}
function parseInput(raw){const input=raw.trim().replace(/\s+/g,' ');let quantity=1,unit='τεμ.',name=input;const first=input.match(/^(\d+(?:[.,]\d+)?)\s+(.+)$/),last=input.match(/^(.+?)\s+(\d+(?:[.,]\d+)?)$/);if(first){quantity=Number(first[1].replace(',','.'));name=first[2]}else if(last){quantity=Number(last[2].replace(',','.'));name=last[1]}const p=name.split(' ');if(p.length>1&&units.includes(p[0].toLowerCase())){unit=p[0];name=p.slice(1).join(' ')}return{name:name.trim()||input,quantity:Number.isFinite(quantity)&&quantity>0?quantity:1,unit}}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selectHtml(values,current){return values.map(v=>`<option ${v===current?'selected':''}>${escapeHtml(v)}</option>`).join('')}
async function boot(){if(!token){show('#authView');return}try{const me=await api('/me');if(!me.household){show('#householdView');return}household=me.household;await enterApp()}catch{localStorage.removeItem('psonia.token');token='';show('#authView')}}
async function enterApp(){show('#appView');$('#houseMeta').textContent=household?.name||'';$('#inviteDisplay').textContent=household?.invite_code||household?.inviteCode||'—';await loadItems();connectRealtime();loadHistory().catch(()=>{})}
async function loadItems(){const d=await api('/items');items=d.items||[];render()}
async function loadHistory(){const d=await api('/activity');$('#historyList').innerHTML=(d.activity||[]).length?(d.activity||[]).map(h=>`<div class="history"><span>${new Date(h.created_at).toLocaleString('el-GR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}</span>${escapeHtml(h.display_name||h.email||'Χρήστης')} • ${escapeHtml(h.action)}${h.item_name?' «'+escapeHtml(h.item_name)+'»':''}</div>`).join(''):'<div class="empty">Δεν υπάρχει ακόμη ιστορικό.</div>'}
function connectRealtime(){eventSource?.close();eventSource=new EventSource(API+`/events?token=${encodeURIComponent(token)}`);eventSource.onmessage=()=>{loadItems().catch(()=>{});loadHistory().catch(()=>{})};eventSource.onerror=()=>{}}
async function addItem(){const el=$('#quickInput'),raw=el.value.trim();if(!raw)return;const p=parseInput(raw),dup=items.find(i=>i.status==='active'&&i.name.toLocaleLowerCase('el')===p.name.toLocaleLowerCase('el'));try{if(dup){await api('/items/'+dup.id,{method:'PATCH',body:JSON.stringify({quantity:Number(dup.quantity)+p.quantity})});toast('Αυξήθηκε η ποσότητα')}else{await api('/items',{method:'POST',body:JSON.stringify({name:p.name,quantity:p.quantity,unit:p.unit})})}el.value='';await loadItems()}catch(e){toast(e.message)}}
async function patch(item,changes){try{await api('/items/'+item.id,{method:'PATCH',body:JSON.stringify(changes)});await loadItems()}catch(e){toast(e.message)}}
function makeItem(item){const node=$('#itemTemplate').content.firstElementChild.cloneNode(true),check=node.querySelector('.check'),main=node.querySelector('.item-main'),icon=node.querySelector('.icon'),editor=node.querySelector('.editor');node.classList.add(item.status);check.textContent=item.status==='purchased'?'✓':'○';icon.textContent=item.status==='deleted'?'↩':'🗑';main.querySelector('strong').textContent=item.name;main.querySelector('span').textContent=`${item.quantity} ${item.unit}${item.store?' • '+item.store:''}${item.category!=='Άλλα'?' • '+item.category:''}`;main.querySelector('small').textContent=item.note||'';check.onclick=()=>patch(item,item.status==='purchased'?{status:'active'}:{status:'purchased'});icon.onclick=()=>patch(item,item.status==='deleted'?{status:'active'}:{status:'deleted'});if(item.status!=='deleted'){editor.innerHTML=`<label>Ποσότητα<input data-k="quantity" type="number" min="0.1" step="0.1" value="${item.quantity}"></label><label>Μονάδα<input data-k="unit" value="${escapeHtml(item.unit)}"></label><label>Κατηγορία<select data-k="category">${selectHtml(categories,item.category)}</select></label><label>Κατάστημα<select data-k="store">${selectHtml(stores,item.store)}</select></label><label class="wide">Σημείωση<input data-k="note" value="${escapeHtml(item.note||'')}" placeholder="π.χ. πλήρες 3,5%"></label><label>Προτεραιότητα<select data-k="priority"><option value="normal" ${item.priority==='normal'?'selected':''}>Κανονικό</option><option value="important" ${item.priority==='important'?'selected':''}>Σημαντικό</option><option value="urgent" ${item.priority==='urgent'?'selected':''}>Επείγον</option></select></label>`;editor.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{const key=el.dataset.k;let value=el.value;if(key==='quantity')value=Number(value)||1;patch(item,{[key]:value})});main.onclick=()=>editor.hidden=!editor.hidden}else main.onclick=()=>{};return node}
function render(){const visible=items.filter(i=>i.name.toLocaleLowerCase('el').includes(query.toLocaleLowerCase('el'))),active=visible.filter(i=>i.status==='active'),purchased=visible.filter(i=>i.status==='purchased'),trash=visible.filter(i=>i.status==='deleted');$('#summary').textContent=`${active.length} προς αγορά • ${purchased.length} αγορασμένα`;fill('#activeList',active,'Η λίστα είναι καθαρή. Πρόσθεσε κάτι.');$('#purchasedSection').hidden=!purchased.length;fill('#purchasedList',purchased);$('#trashSection').hidden=!trash.length;$('#trashSummary').textContent=`Πρόσφατα διαγραμμένα (${trash.length})`;fill('#trashList',trash)}
function fill(sel,list,empty=''){const el=$(sel);el.innerHTML='';if(!list.length&&empty){el.innerHTML=`<div class="empty">${empty}</div>`;return}list.forEach(i=>el.appendChild(makeItem(i)))}
function setTab(tab){['list','history','settings'].forEach(t=>$(`#${t}View`).hidden=t!==tab);$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='history')loadHistory().catch(()=>{})}
function updateNetwork(){const on=navigator.onLine,n=$('#network');if(n){n.textContent=on?'● Online':'● Offline';n.className='status '+(on?'ok':'off')}}
$('#showLogin').onclick=()=>{$('#loginForm').hidden=false;$('#signupForm').hidden=true;$('#showLogin').classList.add('active');$('#showSignup').classList.remove('active')};$('#showSignup').onclick=()=>{$('#loginForm').hidden=true;$('#signupForm').hidden=false;$('#showSignup').classList.add('active');$('#showLogin').classList.remove('active')};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});token=d.token;localStorage.setItem('psonia.token',token);boot()}catch(err){$('#authError').textContent=err.message;$('#authError').hidden=false}};
$('#signupForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/signup',{method:'POST',body:JSON.stringify({displayName:$('#signupName').value,email:$('#signupEmail').value,password:$('#signupPassword').value})});token=d.token;localStorage.setItem('psonia.token',token);show('#householdView')}catch(err){$('#authError').textContent=err.message;$('#authError').hidden=false}};
$('#createHouse').onclick=async()=>{try{const d=await api('/households',{method:'POST',body:JSON.stringify({name:$('#houseName').value||'Το σπίτι μας'})});household=d;await enterApp()}catch(e){$('#houseError').textContent=e.message;$('#houseError').hidden=false}};
$('#joinHouse').onclick=async()=>{try{const d=await api('/households/join',{method:'POST',body:JSON.stringify({inviteCode:$('#inviteCode').value})});household=d;await enterApp()}catch(e){$('#houseError').textContent=e.message;$('#houseError').hidden=false}};
$('#logoutBtn').onclick=()=>{eventSource?.close();token='';localStorage.removeItem('psonia.token');show('#authView')};
$('#addBtn').onclick=addItem;$('#quickInput').onkeydown=e=>{if(e.key==='Enter')addItem()};$('#search').oninput=e=>{query=e.target.value;render()};$('#clearPurchased').onclick=async()=>{for(const i of items.filter(x=>x.status==='purchased'))await patch(i,{status:'deleted'})};$$('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
const theme=localStorage.getItem('psonia.theme')||'system';$('#theme').value=theme;document.documentElement.dataset.theme=theme;$('#theme').onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('psonia.theme',e.target.value)};
addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
updateNetwork();boot();