'use strict';
const ITEMS_KEY='psonia.items.v3', HISTORY_KEY='psonia.history.v3';
const categories=['Άλλα','Φρούτα','Λαχανικά','Κρέας','Ψάρια','Γαλακτοκομικά','Αρτοποιείο','Ποτά','Κατεψυγμένα','Καθαριστικά','Χαρτικά','Προσωπική φροντίδα','Σπίτι'];
const stores=['','Super Market','Lidl','Μανάβικο','Κρεοπωλείο','Φαρμακείο','Jumbo','Άλλο'];
const units=['κιλά','κιλό','kg','γρ','γραμμάρια','τεμάχια','τεμάχιο','μπουκάλια','μπουκάλι','πακέτα','πακέτο'];
let items=load(ITEMS_KEY,[]), history=load(HISTORY_KEY,[]), query='', deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], now=()=>new Date().toISOString(), id=()=>crypto.randomUUID();
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function persist(){localStorage.setItem(ITEMS_KEY,JSON.stringify(items));localStorage.setItem(HISTORY_KEY,JSON.stringify(history.slice(0,200)))}
function log(text){history.unshift({id:id(),text,at:now()});persist()}
function parseInput(raw){const input=raw.trim().replace(/\s+/g,' ');let quantity=1,unit='τεμ.',name=input;const first=input.match(/^(\d+(?:[.,]\d+)?)\s+(.+)$/),last=input.match(/^(.+?)\s+(\d+(?:[.,]\d+)?)$/);if(first){quantity=Number(first[1].replace(',','.'));name=first[2]}else if(last){quantity=Number(last[2].replace(',','.'));name=last[1]}const p=name.split(' ');if(p.length>1&&units.includes(p[0].toLowerCase())){unit=p[0];name=p.slice(1).join(' ')}return{name:name.trim()||input,quantity:Number.isFinite(quantity)&&quantity>0?quantity:1,unit}}
function addItem(){const el=$('#quickInput'),raw=el.value.trim();if(!raw)return;const p=parseInput(raw),dup=items.find(i=>i.status==='active'&&i.name.toLocaleLowerCase('el')===p.name.toLocaleLowerCase('el'));if(dup){dup.quantity+=p.quantity;dup.updatedAt=now();log(`Αυξήθηκε η ποσότητα στο «${dup.name}»`)}else{items.unshift({id:id(),name:p.name,quantity:p.quantity,unit:p.unit,category:'Άλλα',store:'',note:'',priority:'normal',status:'active',createdAt:now(),updatedAt:now()});log(`Προστέθηκε «${p.name}»`)}el.value='';persist();render()}
function patch(item,changes,message){Object.assign(item,changes,{updatedAt:now()});if(message)log(message);persist();render()}
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selectHtml(values,current){return values.map(v=>`<option ${v===current?'selected':''}>${escapeHtml(v)}</option>`).join('')}
function makeItem(item){const node=$('#itemTemplate').content.firstElementChild.cloneNode(true),check=node.querySelector('.check'),main=node.querySelector('.item-main'),icon=node.querySelector('.icon'),editor=node.querySelector('.editor');node.classList.add(item.status);check.textContent=item.status==='purchased'?'✓':'○';check.setAttribute('aria-label',item.status==='purchased'?'Επαναφορά':'Αγοράστηκε');icon.textContent=item.status==='deleted'?'↩':'🗑';icon.setAttribute('aria-label',item.status==='deleted'?'Επαναφορά':'Διαγραφή');main.querySelector('strong').textContent=item.name;main.querySelector('span').textContent=`${item.quantity} ${item.unit}${item.store?' • '+item.store:''}${item.category!=='Άλλα'?' • '+item.category:''}`;main.querySelector('small').textContent=item.note||'';check.onclick=()=>patch(item,item.status==='purchased'?{status:'active',purchasedAt:null}:{status:'purchased',purchasedAt:now()},item.status==='purchased'?`Επαναφέρθηκε «${item.name}» στη λίστα`:`Αγοράστηκε «${item.name}»`);icon.onclick=()=>patch(item,item.status==='deleted'?{status:'active'}:{status:'deleted'},item.status==='deleted'?`Επαναφέρθηκε «${item.name}»`:`Διαγράφηκε «${item.name}»`);if(item.status!=='deleted'){editor.innerHTML=`<label>Ποσότητα<input data-k="quantity" type="number" min="0.1" step="0.1" value="${item.quantity}"></label><label>Μονάδα<input data-k="unit" value="${escapeHtml(item.unit)}"></label><label>Κατηγορία<select data-k="category">${selectHtml(categories,item.category)}</select></label><label>Κατάστημα<select data-k="store">${selectHtml(stores,item.store)}</select></label><label class="wide">Σημείωση<input data-k="note" value="${escapeHtml(item.note)}" placeholder="π.χ. πλήρες 3,5%"></label><label>Προτεραιότητα<select data-k="priority"><option value="normal" ${item.priority==='normal'?'selected':''}>Κανονικό</option><option value="important" ${item.priority==='important'?'selected':''}>Σημαντικό</option><option value="urgent" ${item.priority==='urgent'?'selected':''}>Επείγον</option></select></label>`;editor.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{const key=el.dataset.k;let value=el.value;if(key==='quantity')value=Number(value)||1;patch(item,{[key]:value})});main.onclick=()=>editor.hidden=!editor.hidden}else main.onclick=()=>{};return node}
function render(){const visible=items.filter(i=>i.name.toLocaleLowerCase('el').includes(query.toLocaleLowerCase('el'))),active=visible.filter(i=>i.status==='active'),purchased=visible.filter(i=>i.status==='purchased'),trash=visible.filter(i=>i.status==='deleted');$('#summary').textContent=`${active.length} προς αγορά • ${purchased.length} αγορασμένα`;fill('#activeList',active,'Η λίστα είναι καθαρή. Πρόσθεσε κάτι παραπάνω.');$('#purchasedSection').hidden=!purchased.length;fill('#purchasedList',purchased);$('#trashSection').hidden=!trash.length;$('#trashSummary').textContent=`Πρόσφατα διαγραμμένα (${trash.length})`;fill('#trashList',trash);$('#historyList').innerHTML=history.length?history.map(h=>`<div class="history"><span>${new Date(h.at).toLocaleString('el-GR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}</span>${escapeHtml(h.text)}</div>`).join(''):'<div class="empty">Δεν υπάρχει ακόμη ιστορικό.</div>'}
function fill(sel,list,empty=''){const el=$(sel);el.innerHTML='';if(!list.length&&empty){el.innerHTML=`<div class="empty">${empty}</div>`;return}list.forEach(i=>el.appendChild(makeItem(i)))}
function updateNetwork(){const on=navigator.onLine,n=$('#network');n.textContent=on?'● Online':'● Offline';n.className='status '+(on?'ok':'off')}
function setTab(tab){['list','history','settings'].forEach(t=>$(`#${t}View`).hidden=t!==tab);$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
$('#addBtn').onclick=addItem;$('#quickInput').onkeydown=e=>{if(e.key==='Enter')addItem()};$('#search').oninput=e=>{query=e.target.value;render()};$('#clearPurchased').onclick=()=>{const bought=items.filter(i=>i.status==='purchased');if(bought.length&&confirm('Να μεταφερθούν όλα τα αγορασμένα στα πρόσφατα διαγραμμένα;')){bought.forEach(i=>{i.status='deleted';i.updatedAt=now()});log('Καθαρίστηκαν τα αγορασμένα');persist();render()}};$$('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
const theme=localStorage.getItem('psonia.theme')||'system';$('#theme').value=theme;document.documentElement.dataset.theme=theme;$('#theme').onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('psonia.theme',e.target.value)};
addEventListener('online',()=>{updateNetwork();render()});addEventListener('offline',updateNetwork);addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
updateNetwork();render();